version: '3.8'

services:
  db:
    image: postgres:alpine3.20
    container_name: postgres_db
    environment:
      POSTGRES_USER: gca
      POSTGRES_PASSWORD: gca
      POSTGRES_DB: gym-crm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  activemq:
    image: rmohr/activemq
    ports:
      - "8161:8161"
      - "61616:61616"
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=gcaadmin
      - ACTIVEMQ_ADMIN_PASSWORD=gcaadmin
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml

volumes:
  postgres_data:
