version: '3.8'

services:
  postgres-db:
    image: postgres:alpine3.20
    container_name: postgres_db
    environment:
      POSTGRES_USER: gca
      POSTGRES_PASSWORD: gca
      POSTGRES_DB: gym-crm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mongo-db:
    image: mongo:6.0-rc
    container_name: mongo_db
    environment:
      MONGO_INITDB_ROOT_USERNAME: gca
      MONGO_INITDB_ROOT_PASSWORD: gca
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
  activemq:
    image: rmohr/activemq
    container_name: activemq
    ports:
      - "8161:8161"
      - "61616:61616"
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=gcaadmin
      - ACTIVEMQ_ADMIN_PASSWORD=gcaadmin
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml

volumes:
  postgres_data:
  mongo_data:
