spring:
  application:
    name: gateway-service
  cloud:
    discovery:
      enabled: true
    gateway:
      routes:
        - id: gym-crm-service
          uri: lb://GYM-CRM-SERVICE
          predicates:
            - Path=/gym-crm-service/**
          filters:
            - AuthenticationFilter
            - AddRequestHeader=X-Request-Gateway, Gateway
            - RewritePath=/gym-crm-service/(?<segment>.*), /${segment}
            - name: CircuitBreaker
              args:
                name: gymCrmServiceCircuitBreaker
                fallbackUri: forward:/fallback/gym-crm-service
        - id: trainer-hours-service
          uri: lb://TRAINER-HOURS-SERVICE
          predicates:
            - Path=/trainer-hours-service/**
          filters:
            - AuthenticationFilter
            - AddRequestHeader=X-Request-Gateway, Gateway
            - RewritePath=/trainer-hours-service/(?<segment>.*), /${segment}
            - name: CircuitBreaker
              args:
                name: trainerHoursServiceCircuitBreaker
                fallbackUri: forward:/fallback/trainer-hours-service
        - id: authentication-service
          uri: lb://AUTHENTICATION-SERVICE
          predicates:
            - Path=/authentication-service/**
          filters:
            - AuthenticationFilter
            - AddRequestHeader=X-Request-Gateway, Gateway
            - RewritePath=/authentication-service/(?<segment>.*), /${segment}
            - name: CircuitBreaker
              args:
                name: AuthenticationServiceCircuitBreaker
                fallbackUri: forward:/fallback/authentication-service
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH
  boot:
    admin:
      client:
        url: http://localhost:8090
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    hostname: ${spring.application.name}
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
resilience4j:
  circuitbreaker:
    instances:
      gymCrmServiceCircuitBreaker:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 5
      trainerHoursServiceCircuitBreaker:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state:
          seconds: 5
logging:
  level:
    org.springframework.cloud.gateway: DEBUG