spring:
  application:
    name: discovery-service
  config:
    import: optional:file:.env[.properties]
  boot:
    admin:
      client:
        url: ${ADMIN_SERVICE_URL}
server:
  port: 8761
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
  server:
    enable-self-preservation: false
    eviction-interval-timer-in-ms: 60000
  instance:
    hostname: ${EUREKA_HOST_NAME}
  dashboard:
    enabled: true