server:
  port: 8082
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: trainer-hours-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: trainer_hours
      username: gca
      password: gca
      authentication-database: admin
  cloud:
    discovery:
      enabled: true
    config:
      enabled: false
      discovery:
        enabled: true
  boot:
    admin:
      client:
        url: http://localhost:8090
  jms:
    cache:
      enabled: false
  activemq:
    broker-url: ${BROKER_URL}
    user: ${BROKER_USER}
    password: ${BROKER_PASSWORD}
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    hostname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always