server:
  port: 8082
spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: trainer-hours-service
  data:
    mongodb:
      host: ${MONGO_DB_HOST}
      port: ${MONGO_DB_PORT}
      database: ${MONGO_DB_DATABASE}
      username: ${MONGO_DB_USERNAME}
      password: ${MONGO_DB_PASSWORD}
      authentication-database: admin
      auto-index-creation: true
  cloud:
    discovery:
      enabled: true
    config:
      enabled: false
      discovery:
        enabled: true
  boot:
    admin:
      client:
        url: ${ADMIN_SERVICE_URL}
  jms:
    cache:
      enabled: false
  activemq:
    broker-url: ${BROKER_URL}
    user: ${BROKER_USER}
    password: ${BROKER_PASSWORD}
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    hostname: ${spring.application.name}
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always