server:
  port: 8082
spring:
  application:
    name: trainer-hours-service
  datasource:
    url: jdbc:h2:mem:trainer-hours-db
    username: ths
    password: ths
    driver-class-name: org.h2.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  h2:
    console:
      enabled: true
  cloud:
    discovery:
      enabled: true
  boot:
    admin:
      client:
        url: http://localhost:8090
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    hostname: ${spring.application.name}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always