version: '3.8'

services:
  eureka-service:
    build:
      context: ../
      dockerfile: discovery-service/Dockerfile
    image: eureka-service:1.0
    environment:
      ADMIN_SERVICE_URL: http://admin-service:8090
      EUREKA_HOST_NAME: docker.host
  gateway-service:
    build:
      context: ../
      dockerfile: gateway-service/Dockerfile
    image: gateway-service:1.0
    environment:
      ADMIN_SERVICE_URL: http://admin-service:8090
      EUREKA_SERVICE_URL: http://eureka-service:8761/eureka/
  admin-service:
    build:
      context: ../
      dockerfile: admin-service/Dockerfile
    image: admin-service:1.0
    environment:
      EUREKA_SERVICE_URL: http://eureka-service:8761/eureka/
  config-service:
    build:
      context: ../
      dockerfile: config-service/Dockerfile
    image: config-service:1.0
    environment:
      ADMIN_SERVICE_URL: http://admin-service:8090
      EUREKA_SERVICE_URL: http://eureka-service:8761/eureka/
  authentication-service:
    build:
      context: ../
      dockerfile: authentication-service/Dockerfile
    image: authentication-service:1.0
    environment:
      POSTGRES_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/gym-crm
      POSTGRES_DATASOURCE_USERNAME: gca
      POSTGRES_DATASOURCE_PASSWORD: gca
      ADMIN_SERVICE_URL: http://admin-service:8090
      EUREKA_SERVICE_URL: http://eureka-service:8761/eureka/
  gym-crm-app:
    build:
      context: ../
      dockerfile: gym-crm-service/Dockerfile
    image: gym-crm-app:1.0
    environment:
      POSTGRES_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/gym-crm
      POSTGRES_DATASOURCE_USERNAME: gca
      POSTGRES_DATASOURCE_PASSWORD: gca
      BROKER_URL: tcp://activemq:61616
      BROKER_USER: gcaadmin
      BROKER_PASSWORD: gcaadmin
      ADMIN_SERVICE_URL: http://admin-service:8090
      EUREKA_SERVICE_URL: http://eureka-service:8761/eureka/
  trainer-hours-service:
    build:
      context: ../
      dockerfile: trainer-hours-service/Dockerfile
    image: trainer-hours-service:1.0
    environment:
      MONGO_DB_HOST: mongo-db
      MONGO_DB_PORT: 27017
      MONGO_DB_DATABASE: trainer_hours
      MONGO_DB_USERNAME: gca
      MONGO_DB_PASSWORD: gca
      BROKER_URL: tcp://activemq:61616
      BROKER_USER: gcaadmin
      BROKER_PASSWORD: gcaadmin
      ADMIN_SERVICE_URL: http://admin-service:8090
      EUREKA_SERVICE_URL: http://eureka-service:8761/eureka/
  postgres-db:
    image: postgres:alpine3.20
    environment:
      POSTGRES_USER: gca
      POSTGRES_PASSWORD: gca
      POSTGRES_DB: gym-crm
    volumes:
      - postgres_data:/var/lib/postgresql/data
  mongo-db:
    image: mongo:6.0-rc
    environment:
      MONGO_INITDB_ROOT_USERNAME: gca
      MONGO_INITDB_ROOT_PASSWORD: gca
    volumes:
      - mongo_data:/data/db
  activemq:
    image: rmohr/activemq
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=gcaadmin
      - ACTIVEMQ_ADMIN_PASSWORD=gcaadmin

volumes:
  postgres_data:
  mongo_data:
