spring:
  application:
    name: config-service
  config:
    import: optional:file:.env[.properties]
  profiles:
    active: native
  boot:
    admin:
      client:
        url: ${ADMIN_SERVICE_URL}
  cloud:
    discovery:
      enabled: true
    config:
      server:
        native:
          search-locations: file:/config
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.cloud.client.hostname}:${spring.application.instance_id:${random.value}}
    hostname: ${spring.application.name}
  client:
    service-url:
      defaultZone: ${EUREKA_SERVICE_URL}
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
server:
  port: 8100